//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service/", ConfigurationName="ServiceReference1.Poloniex")]
    public interface Poloniex {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service/Poloniex/rechercheRequest", ReplyAction="http://service/Poloniex/rechercheResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Client.ServiceReference1.rechercheResponse recherche(Client.ServiceReference1.rechercheRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service/")]
    public partial class cryotCurrency : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string designationField;
        
        private double eUROField;
        
        private bool eUROFieldSpecified;
        
        private int numField;
        
        private double uSDField;
        
        private bool uSDFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string designation {
            get {
                return this.designationField;
            }
            set {
                this.designationField = value;
                this.RaisePropertyChanged("designation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double EURO {
            get {
                return this.eUROField;
            }
            set {
                this.eUROField = value;
                this.RaisePropertyChanged("EURO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EUROSpecified {
            get {
                return this.eUROFieldSpecified;
            }
            set {
                this.eUROFieldSpecified = value;
                this.RaisePropertyChanged("EUROSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int num {
            get {
                return this.numField;
            }
            set {
                this.numField = value;
                this.RaisePropertyChanged("num");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double USD {
            get {
                return this.uSDField;
            }
            set {
                this.uSDField = value;
                this.RaisePropertyChanged("USD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool USDSpecified {
            get {
                return this.uSDFieldSpecified;
            }
            set {
                this.uSDFieldSpecified = value;
                this.RaisePropertyChanged("USDSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recherche", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class rechercheRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Type;
        
        public rechercheRequest() {
        }
        
        public rechercheRequest(string Type) {
            this.Type = Type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rechercheResponse", WrapperNamespace="http://service/", IsWrapped=true)]
    public partial class rechercheResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Client.ServiceReference1.cryotCurrency @return;
        
        public rechercheResponse() {
        }
        
        public rechercheResponse(Client.ServiceReference1.cryotCurrency @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PoloniexChannel : Client.ServiceReference1.Poloniex, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PoloniexClient : System.ServiceModel.ClientBase<Client.ServiceReference1.Poloniex>, Client.ServiceReference1.Poloniex {
        
        public PoloniexClient() {
        }
        
        public PoloniexClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PoloniexClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PoloniexClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PoloniexClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.rechercheResponse Client.ServiceReference1.Poloniex.recherche(Client.ServiceReference1.rechercheRequest request) {
            return base.Channel.recherche(request);
        }
        
        public Client.ServiceReference1.cryotCurrency recherche(string Type) {
            Client.ServiceReference1.rechercheRequest inValue = new Client.ServiceReference1.rechercheRequest();
            inValue.Type = Type;
            Client.ServiceReference1.rechercheResponse retVal = ((Client.ServiceReference1.Poloniex)(this)).recherche(inValue);
            return retVal.@return;
        }
    }
}
