
package service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Poloniex", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Poloniex {


    /**
     * 
     * @param type
     * @return
     *     returns service.CryotCurrency
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "recherche", targetNamespace = "http://service/", className = "service.Recherche")
    @ResponseWrapper(localName = "rechercheResponse", targetNamespace = "http://service/", className = "service.RechercheResponse")
    @Action(input = "http://service/Poloniex/rechercheRequest", output = "http://service/Poloniex/rechercheResponse")
    public CryotCurrency recherche(
        @WebParam(name = "Type", targetNamespace = "")
        String type);

}
